require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.harpoon")
require("core.plugin_config.mason")
require("core.plugin_config.LSP")
require("core.plugin_config.nvimTree")
